[package]
authors = ["Peltoche <dev@halium.fr>"]
categories = ["parsing"]
description = "Ical/Vcard parser for Rust"
documentation = "https://peltoche.github.io/ical-rs/ical/index.html"
homepage = "https://github.com/Peltoche/ical-rs"
keywords = ["ical", "vcard", "parser"]
license-file = "GPLv3"
name = "ical"
readme = "./README.md"
repository = "https://github.com/Peltoche/ical-rs"
version = "0.4.0"

[badges]

[badges.travis-ci]
branch = "master"
repository = "Peltoche/ical-rs"



[dependencies]
error-chain = "0.10.0"


[features]
default = ["vcard", "ical"]
ical = ["property"]
line = []
property = ["line"]
vcard = ["property"]

[lib]
doc = true
name = "ical"
path = "src/lib.rs"
test = true
